<?php
/**
 * Chronolabs Digital Signature Generation & API Services (Psuedo-legal correct binding measure)
 *
 * You may not change or alter any portion of this comment or credits
 * of supporting developers from this source code or any supporting source code
 * which is considered copyrighted (c) material of the original comment or credit authors.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * @copyright       Chronolabs Cooperative http://labs.coop
 * @license			General Software Licence (http://labs.coop/briefs/legal/general-software-license/10,3.html)
 * @license			End User License (http://labs.coop/briefs/legal/end-user-license/11,3.html)
 * @license			Privacy and Mooching Policy (http://labs.coop/briefs/legal/privacy-and-mooching-policy/22,3.html)
 * @license			General Public Licence 3 (http://labs.coop/briefs/legal/general-public-licence/13,3.html)
 * @category		signed
 * @since			2.1.9
 * @version			2.2.0
 * @author			Simon Antony Roberts (Aus Passport: M8747409) <wishcraft@users.sourceforge.net>
 * @author          Simon Antony Roberts (Aus Passport: M8747409) <wishcraft@users.sourceforge.net>
 * @subpackage		module-data
 * @description		Digital Signature Generation & API Services (Psuedo-legal correct binding measure)
 * @link			Farming Digital Fingerprint Signatures: https://signed.ringwould.com.au
 * @link			Heavy Hash-info Digital Fingerprint Signature: http://signed.hempembassy.net
 * @link			XOOPS SVN: https://sourceforge.net/p/xoops/svn/HEAD/tree/XoopsModules/signed/
 * @see				Release Article: http://cipher.labs.coop/portfolio/signed-identification-validations-and-signer-for-xoops/
 * @filesource
 *
 */

error_reporting(E_ALL);

if (file_exists($blowfish = __DIR__ . DIRECTORY_SEPARATOR . 'include' . DIRECTORY_SEPARATOR . 'blowfish-salt.php'))
{
	require_once($blowfish);
	if (constant("SIGNED_BLOWFISH_SALT") != "%%%%%%%%%%%%%%%%%%%%%")
	{
		chmod($blowfish, 0444);
	} else {
		$module_handler = xoops_gethandler('module');
		$signedModule = $module_handler->getByDirname(basename(__DIR__));
		if (is_object($signedModule) && is_object($GLOBALS['xoopsUser']))
		{
			if (!strpos($_SERVER["REQUEST_URI"], "signed/admin/salty.php") && $GLOBALS['xoopsUser']->isAdmin())
				redirect_header(XOOPS_URL . '/modules/signed/admin/salty.php', 7, _SIGNED_MI_REDIRECT_SALTYGENNEEDED);
		}
	}
}

$modversion                   = array();
$modversion['name']           = _SIGNED_MI_MODULE_NAME;
$modversion['version']        = _SIGNED_MI_MODULE_VERSION;
$modversion['description']    = _SIGNED_MI_MODULE_DESCRIPTION;
$modversion['author']         = _SIGNED_MI_MODULE_AUTHOR;
$modversion['credits']        = _SIGNED_MI_MODULE_CREDITS;
$modversion['help']           = 'page=help';
$modversion['license']        = 'Chronolabs GSL';
$modversion['license_url']    = "labs.coop/briefs/legal/general-software-license/10,3.html";
$modversion['image']          = "image/signed.png";
$modversion['dirname']        = "signed";
$modversion['dirmoduleadmin'] = '/Frameworks/moduleclasses/moduleadmin';
$modversion['icons16']        = 'image/icons/16';
$modversion['icons32']        = 'image/icons/32';

//about
$modversion["module_status"]       = "Major Final";
$modversion['release_date']        = '2014/06/14';
$modversion["module_website_url"]  = "http://labs.coop/";
$modversion["module_website_name"] = "Chronolabs Cooperative";
$modversion['min_php']             = '5.3.7';
$modversion['min_xoops']           = "2.5.7";
$modversion['min_admin']           = '1.1';
$modversion['min_db']              = array(
    'mysql'  => '5.0.7',
    'mysqli' => '5.0.7'
);

// Admin menu
// Set to 1 if you want to display menu generated by system module
$modversion['system_menu'] = !strpos($_SERVER["REQUEST_URI"], "signed/admin/salty.php");

// Admin things
$modversion['hasAdmin']   = 1;
$modversion['adminindex'] = "admin/admin.php";
$modversion['adminmenu']  = "admin/menu.php";

// Mysql file
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";

// Table
$modversion['tables'][0] = "signed_signatures";
$modversion['tables'][1] = "signed_events";
$modversion['tables'][2] = "signed_event_links";
$modversion['tables'][3] = "signed_keiyes";


// Templates
$modversion['templates']                   = array();
$modversion['templates'][1]['file']        = 'signed_wrapper.html';
$modversion['templates'][1]['description'] = 'Digital Self Signinf ~ HTML Wrapper';


// Menu
$modversion['hasMain'] = 1;


//update things
$modversion['onUpdate'] = 'include/upgrade-module.php';

$modversion['config']   = array();
$modversion['config'][] = array(
		'name'        => 'memory_limits',
		'title'       => '_SIGNED_MI_MEMORY_LIMITS',
		'description' => '_SIGNED_MI_MEMORY_LIMITS_DESC',
		'formtype'    => 'text',
		'valuetype'   => 'int',
		'default'     => 396
);

$modversion['config'][] = array(
		'name'        => 'compression',
		'title'       => '_SIGNED_MI_COMPRESSION',
		'description' => '_SIGNED_MI_COMPRESSION_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => true
);

$modversion['config'][] = array(
		'name'        => 'encryption',
		'title'       => '_SIGNED_MI_ENCRYPTION',
		'description' => '_SIGNED_MI_ENCRYPTION_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => false
);

$cryptus_handler = xoops_getmodulehandler('cryptus', $modversion['dirname']);
$modversion['config'][] = array(
		'name'        => 'ciphers',
		'title'       => '_SIGNED_MI_CIPHERS',
		'description' => '_SIGNED_MI_CIPHERS_DESC',
		'formtype'    => 'select_multi',
		'valuetype'   => 'array',
		'default'     => $cryptus_handler->getAllByTypals(true, array('rsa-openssl')),
		'options'     => $cryptus_handler->getAllByTypals(false, array('rsa-openssl'))
);

$modversion['config'][] = array(
		'name'        => 'pem-key',
		'title'       => '_SIGNED_MI_SSLPEMKEY_PATH',
		'description' => '_SIGNED_MI_SSLPEMKEY_PATH_DESC',
		'formtype'    => 'text',
		'valuetype'   => 'text',
		'default'     => ''
);

$modversion['config'][] = array(
		'name'        => 'ocr',
		'title'       => '_SIGNED_MI_USEOCR',
		'description' => '_SIGNED_MI_USEOCR_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => false
);

$modversion['config'][] = array(
		'name'        => 'ocr-api-uri',
		'title'       => '_SIGNED_MI_OCRAPI',
		'description' => '_SIGNED_MI_OCRAPI_DESC',
		'formtype'    => 'text',
		'valuetype'   => 'text',
		'default'     => 'http://ocr.labs.coop'
);

$modversion['config'][] = array(
		'name'        => 'htaccess',
		'title'       => '_SIGNED_MI_HTACCESS',
		'description' => '_SIGNED_MI_HTACCESS_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => false
);

$modversion['config'][] = array(
		'name'        => 'htaccess_path',
		'title'       => '_SIGNED_MI_HTACCESS_PATH',
		'description' => '_SIGNED_MI_HTACCESS_PATH_DESC',
		'formtype'    => 'text',
		'valuetype'   => 'text',
		'default'     => '/signing'
);

$modversion['config'][] = array(
		'name'        => 'htaccess_url_api',
		'title'       => '_SIGNED_MI_HTACCESS_URL_API',
		'description' => '_SIGNED_MI_HTACCESS_URL_API_DESC',
		'formtype'    => 'text',
		'valuetype'   => 'text',
		'default'     => XOOPS_URL . '/signer'
);


$modversion['config'][] = array(
		'name'        => 'htaccess_extension',
		'title'       => '_SIGNED_MI_HTACCESS_EXTENSION',
		'description' => '_SIGNED_MI_HTACCESS_EXTENSION_DESC',
		'formtype'    => 'text',
		'valuetype'   => 'text',
		'default'     => '.html'
);


$modversion['config'][] = array(
		'name'        => 'title',
		'title'       => '_SIGNED_MI_TITLE',
		'description' => '_SIGNED_MI_TITLE_DESC',
		'formtype'    => 'text',
		'valuetype'   => 'text',
		'default'     => 'Digital Signatures'
);

$modversion['config'][] = array(
		'name'        => 'email',
		'title'       => '_SIGNED_MI_EMAIL',
		'description' => '_SIGNED_MI_EMAIL_DESC',
		'formtype'    => 'text',
		'valuetype'   => 'text',
		'default'     => $GLOBALS['xoopsConfig']['adminmail']
);

$modversion['config'][] = array(
		'name'        => 'use_ssl',
		'title'       => '_SIGNED_MI_USE_SSL',
		'description' => '_SIGNED_MI_USE_SSL_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => false
);

$modversion['config'][] = array(
		'name'        => 'verify_email',
		'title'       => '_SIGNED_MI_VERIFY_EMAIL',
		'description' => '_SIGNED_MI_VERIFY_EMAIL_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => true
);

$modversion['config'][] = array(
		'name'        => 'verify_mobile',
		'title'       => '_SIGNED_MI_VERIFY_MOBILE',
		'description' => '_SIGNED_MI_VERIFY_MOBILE_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => false
);

$modversion['config'][] = array(
    'name'        => 'php_timezone',
    'title'       => '_SIGNED_MI_PHPTIMEZONE',
    'description' => '_SIGNED_MI_PHPTIMEZONE_DESC',
    'formtype'    => 'text',
    'valuetype'   => 'text',
    'default'     => 'Australia/Sydney'
);

$modversion['config'][] = array(
    'name'        => 'years_numberof',
    'title'       => '_SIGNED_MI_YEARS_NUMBEROF',
    'description' => '_SIGNED_MI_YEARS_NUMBEROF_DESC',
    'formtype'    => 'textbox',
    'valuetype'   => 'int',
    'default'     => 14
);

$modversion['config'][] = array(
		'name'        => 'watermark_gif',
		'title'       => '_SIGNED_MI_WATERMARK_GIF',
		'description' => '_SIGNED_MI_WATERMARK_GIF_DESC',
		'formtype'    => 'text',
		'valuetype'   => 'text',
		'default'     => 'watermark.gif'
);

$modversion['config'][] = array(
		'name'        => 'watermark_weight',
		'title'       => '_SIGNED_MI_WATERMARK_WEIGHT',
		'description' => '_SIGNED_MI_WATERMARK_WEIGHT_DESC',
		'formtype'    => 'textbox',
		'valuetype'   => 'float',
		'default'     => 1.25
);

$modversion['config'][] = array(
		'name'        => 'watermark_scale',
		'title'       => '_SIGNED_MI_WATERMARK_SCALE',
		'description' => '_SIGNED_MI_WATERMARK_SCALE_DESC',
		'formtype'    => 'textbox',
		'valuetype'   => 'float',
		'default'     => 3.75
);

$modversion['config'][] = array(
		'name'        => 'watermark_min_opacity',
		'title'       => '_SIGNED_MI_WATERMARK_MINOPACITY',
		'description' => '_SIGNED_MI_WATERMARK_MINOPACITY_DESC',
		'formtype'    => 'textbox',
		'valuetype'   => 'int',
		'default'     => 32
);

$modversion['config'][] = array(
		'name'        => 'watermark_max_opacity',
		'title'       => '_SIGNED_MI_WATERMARK_MAXOPACITY',
		'description' => '_SIGNED_MI_WATERMARK_MAXOPACITY_DESC',
		'formtype'    => 'textbox',
		'valuetype'   => 'int',
		'default'     => 82
);

$modversion['config'][] = array(
		'name'        => 'errors_logged',
		'title'       => '_SIGNED_MI_ERRORS_LOGGED',
		'description' => '_SIGNED_MI_ERRORS_LOGGED_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => false
);

$modversion['config'][] = array(
		'name'        => 'errors_displayed',
		'title'       => '_SIGNED_MI_ERRORS_DISPLAYED',
		'description' => '_SIGNED_MI_ERRORS_DISPLAYED_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => false
);

$modversion['config'][] = array(
		'name'        => 'errors_reporting',
		'title'       => '_SIGNED_MI_ERRORS_REPORTING',
		'description' => '_SIGNED_MI_ERRORS_REPORTING_DESC',
		'formtype'    => 'select',
		'valuetype'   => 'int',
		'options' 	  => array('All Errors' => E_ALL, 'Critical Only' => E_ERROR, 'Notices Only' => E_NOTICE, 'Warnings Only' => E_WARNING), 
		'default'     => E_ERROR
);

$modversion['config'][] = array(
		'name'        => 'discoverable',
		'title'       => '_SIGNED_MI_DISCOVERABLE',
		'description' => '_SIGNED_MI_DISCOVERABLE_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => true
);

$modversion['config'][] = array(
		'name'        => 'storage',
		'title'       => '_SIGNED_MI_STORAGE',
		'description' => '_SIGNED_MI_STORAGE_DESC',
		'formtype'    => 'select',
		'valuetype'   => 'text',
		'options' 	  => array(_SIGNED_MI_FORMAT_JSON => 'json', _SIGNED_MI_FORMAT_SERIAL => 'serial', _SIGNED_MI_FORMAT_XML => 'xml'),
		'default'     => 'json'
);

$modversion['config'][] = array(
		'name'        => 'storage_logs',
		'title'       => '_SIGNED_MI_STORAGE_LOGS',
		'description' => '_SIGNED_MI_STORAGE_LOGS_DESC',
		'formtype'    => 'select',
		'valuetype'   => 'text',
		'options' 	  => array(_SIGNED_MI_FORMAT_JSON => 'json', _SIGNED_MI_FORMAT_SERIAL => 'serial', _SIGNED_MI_FORMAT_XML => 'xml'),
		'default'     => 'json'
);

$modversion['config'][] = array(
		'name'        => 'storage_signed',
		'title'       => '_SIGNED_MI_STORAGE_SIGNED',
		'description' => '_SIGNED_MI_STORAGE_SIGNED_DESC',
		'formtype'    => 'select',
		'valuetype'   => 'text',
		'options' 	  => array(_SIGNED_MI_FORMAT_JSON => 'json', _SIGNED_MI_FORMAT_SERIAL => 'serial', _SIGNED_MI_FORMAT_XML => 'xml'),
		'default'     => 'json'
);

$modversion['config'][] = array(
		'name'        => 'storage_resources',
		'title'       => '_SIGNED_MI_STORAGE_RESOURCES',
		'description' => '_SIGNED_MI_STORAGE_RESOURCES_DESC',
		'formtype'    => 'select',
		'valuetype'   => 'text',
		'options' 	  => array(_SIGNED_MI_FORMAT_JSON => 'json', _SIGNED_MI_FORMAT_SERIAL => 'serial', _SIGNED_MI_FORMAT_XML => 'xml'),
		'default'     => 'json'
);

$modversion['config'][] = array(
		'name'        => 'storage_urls',
		'title'       => '_SIGNED_MI_STORAGE_URLS',
		'description' => '_SIGNED_MI_STORAGE_URLS_DESC',
		'formtype'    => 'select',
		'valuetype'   => 'text',
		'options' 	  => array(_SIGNED_MI_FORMAT_JSON => 'json', _SIGNED_MI_FORMAT_SERIAL => 'serial', _SIGNED_MI_FORMAT_XML => 'xml'),
		'default'     => 'json'
);

$modversion['config'][] = array(
		'name'        => 'logo_width',
		'title'       => '_SIGNED_MI_LOGOWIDTH',
		'description' => '_SIGNED_MI_LOGOWIDTH_DESC',
		'formtype'    => 'textbox',
		'valuetype'   => 'int',
		'default'     => 320
);

$modversion['config'][] = array(
		'name'        => 'logo_height',
		'title'       => '_SIGNED_MI_LOGOHEIGHT',
		'description' => '_SIGNED_MI_LOGOHEIGHT_DESC',
		'formtype'    => 'textbox',
		'valuetype'   => 'int',
		'default'     => 320
);

$modversion['config'][] = array(
		'name'        => 'photo_width',
		'title'       => '_SIGNED_MI_PHOTOWIDTH',
		'description' => '_SIGNED_MI_PHOTOWIDTH_DESC',
		'formtype'    => 'textbox',
		'valuetype'   => 'int',
		'default'     => 340
);

$modversion['config'][] = array(
		'name'        => 'photo_height',
		'title'       => '_SIGNED_MI_PHOTOHEIGHT',
		'description' => '_SIGNED_MI_PHOTOHEIGHT_DESC',
		'formtype'    => 'textbox',
		'valuetype'   => 'int',
		'default'     => 375
);

$modversion['config'][] = array(
		'name'        => 'api_user',
		'title'       => '_SIGNED_MI_API_USER',
		'description' => '_SIGNED_MI_API_USER_DESC',
		'formtype'    => 'text',
		'valuetype'   => 'text',
		'default'     => ''
); 

$modversion['config'][] = array(
		'name'        => 'api_format',
		'title'       => '_SIGNED_MI_API_FORMAT',
		'description' => '_SIGNED_MI_API_FORMAT_DESC',
		'formtype'    => 'select',
		'valuetype'   => 'text',
		'options' 	  => array(_SIGNED_MI_FORMAT_JSON => 'json', _SIGNED_MI_FORMAT_SERIAL => 'serial', _SIGNED_MI_FORMAT_XML => 'xml'),
		'default'     => 'json'
);

$modversion['config'][] = array(
		'name'        => 'api_enabled',
		'title'       => '_SIGNED_MI_API_ENABLED',
		'description' => '_SIGNED_MI_API_ENABLED_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => true
);

$modversion['config'][] = array(
		'name'        => 'api_sign',
		'title'       => '_SIGNED_MI_API_SIGN',
		'description' => '_SIGNED_MI_API_SIGN_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => true
);

$modversion['config'][] = array(
		'name'        => 'api_verify',
		'title'       => '_SIGNED_MI_API_VERIFY',
		'description' => '_SIGNED_MI_API_VERIFY_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => true
);


$modversion['config'][] = array(
		'name'        => 'api_verification',
		'title'       => '_SIGNED_MI_API_VERIFICATION',
		'description' => '_SIGNED_MI_API_VERIFICATION_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => true
);

$modversion['config'][] = array(
		'name'        => 'api_sites',
		'title'       => '_SIGNED_MI_API_SITES',
		'description' => '_SIGNED_MI_API_SITES_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => true
);


$modversion['config'][] = array(
		'name'        => 'api_languages',
		'title'       => '_SIGNED_MI_API_LANGUAGES',
		'description' => '_SIGNED_MI_API_LANGUAGES_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => true
);

$modversion['config'][] = array(
		'name'        => 'api_classes',
		'title'       => '_SIGNED_MI_API_CLASSES',
		'description' => '_SIGNED_MI_API_CLASSES_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => true
);

$modversion['config'][] = array(
		'name'        => 'api_descriptions',
		'title'       => '_SIGNED_MI_API_DESCRIPTIONS',
		'description' => '_SIGNED_MI_API_DESCRIPTIONS_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => true
);

$modversion['config'][] = array(
		'name'        => 'api_enumerators',
		'title'       => '_SIGNED_MI_API_ENUMERATORS',
		'description' => '_SIGNED_MI_API_ENUMERATORS_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => true
);

$modversion['config'][] = array(
		'name'        => 'api_fields',
		'title'       => '_SIGNED_MI_API_FIELDS',
		'description' => '_SIGNED_MI_API_FIELDS_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => true
);

$modversion['config'][] = array(
		'name'        => 'api_fieldtypes',
		'title'       => '_SIGNED_MI_API_FIELDTYPES',
		'description' => '_SIGNED_MI_API_FIELDTYPES_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => true
);

$modversion['config'][] = array(
		'name'        => 'api_identifications',
		'title'       => '_SIGNED_MI_API_IDENTIFICATIONS',
		'description' => '_SIGNED_MI_API_IDENTIFICATIONS_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => true
);

$modversion['config'][] = array(
		'name'        => 'api_prompts',
		'title'       => '_SIGNED_MI_API_PROMPTS',
		'description' => '_SIGNED_MI_API_PROMPTS_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => true
);

$modversion['config'][] = array(
		'name'        => 'api_providers',
		'title'       => '_SIGNED_MI_API_PROVIDERS',
		'description' => '_SIGNED_MI_API_PROVIDERS_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => true
);

$modversion['config'][] = array(
		'name'        => 'api_signatures',
		'title'       => '_SIGNED_MI_API_SIGNATURES',
		'description' => '_SIGNED_MI_API_SIGNATURES_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => true
);

$modversion['config'][] = array(
		'name'        => 'api_validations',
		'title'       => '_SIGNED_MI_API_VALIDATIONS',
		'description' => '_SIGNED_MI_API_VALIDATIONS_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => true
);

$modversion['config'][] = array(
		'name'        => 'api_processes',
		'title'       => '_SIGNED_MI_API_PROCESSES',
		'description' => '_SIGNED_MI_API_PROCESSES_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => true
);

$modversion['config'][] = array(
		'name'        => 'api_language',
		'title'       => '_SIGNED_MI_API_LANGAUGE',
		'description' => '_SIGNED_MI_API_LANGAUGE_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => true
);

$modversion['config'][] = array(
		'name'        => 'api_states',
		'title'       => '_SIGNED_MI_API_STATES',
		'description' => '_SIGNED_MI_API_STATES_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => true
);

$modversion['config'][] = array(
		'name'        => 'api_request',
		'title'       => '_SIGNED_MI_API_REQUEST',
		'description' => '_SIGNED_MI_API_REQUEST_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => true
);

$modversion['config'][] = array(
		'name'        => 'api_banned',
		'title'       => '_SIGNED_MI_API_BANNED',
		'description' => '_SIGNED_MI_API_BANNED_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => true
);

$modversion['config'][] = array(
		'name'        => 'banning_cookie',
		'title'       => '_SIGNED_MI_BANNING_COOKIE',
		'description' => '_SIGNED_MI_BANNING_COOKIE_DESC',
		'formtype'    => 'text',
		'valuetype'   => 'text',
		'default'     => 'signed-xoops-pointers'
);


$modversion['config'][] = array(
		'name'        => 'email_fromaddr',
		'title'       => '_SIGNED_MI_EMAIL_FROMADDR',
		'description' => '_SIGNED_MI_EMAIL_FROMADDR_DESC',
		'formtype'    => 'text',
		'valuetype'   => 'text',
		'default'     => $GLOBALS['xoopsConfig']['adminmail']
);

$modversion['config'][] = array(
		'name'        => 'email_fromname',
		'title'       => '_SIGNED_MI_EMAIL_FROMNAME',
		'description' => '_SIGNED_MI_EMAIL_FROMNAME_DESC',
		'formtype'    => 'text',
		'valuetype'   => 'text',
		'default'     => $GLOBALS['xoopsConfig']['sitename'] . ' Digital Signatures'
);

$modversion['config'][] = array(
		'name'        => 'email_priority',
		'title'       => '_SIGNED_MI_EMAIL_PRIORITY',
		'description' => '_SIGNED_MI_EMAIL_PRIORITY_DESC',
		'formtype'    => 'select',
		'valuetype'   => 'text',
		'options'     => array( _SIGNED_MI_OPTION_EMAIL_PRIORITY_HIGH => 'high', _SIGNED_MI_OPTION_EMAIL_PRIORITY_NORMAL => 'normal', _SIGNED_MI_OPTION_EMAIL_PRIORITY_LOW => 'low'),
		'default'     => 'high'
);

$modversion['config'][] = array(
		'name'        => 'email_method',
		'title'       => '_SIGNED_MI_EMAIL_METHOD',
		'description' => '_SIGNED_MI_EMAIL_METHOD_DESC',
		'formtype'    => 'select',
		'valuetype'   => 'text',
		'options'     => array('PHP Mail' => 'mail','SMTP Authenticated' => 'smtp','Sendmail' => 'sendmail'),
		'default'     => 'mail'
);

$modversion['config'][] = array(
		'name'        => 'email_smtp_host',
		'title'       => '_SIGNED_MI_EMAIL_SMTP_HOST',
		'description' => '_SIGNED_MI_EMAIL_SMTP_HOST_DESC',
		'formtype'    => 'text',
		'valuetype'   => 'text',
		'default'     => ''
);

$modversion['config'][] = array(
		'name'        => 'email_smtp_user',
		'title'       => '_SIGNED_MI_EMAIL_SMTP_USER',
		'description' => '_SIGNED_MI_EMAIL_SMTP_USER_DESC',
		'formtype'    => 'text',
		'valuetype'   => 'text',
		'default'     => ''
);

$modversion['config'][] = array(
		'name'        => 'email_smtp_pass',
		'title'       => '_SIGNED_MI_EMAIL_SMTP_PASS',
		'description' => '_SIGNED_MI_EMAIL_SMTP_PASS_DESC',
		'formtype'    => 'password',
		'valuetype'   => 'text',
		'default'     => ''
);

$modversion['config'][] = array(
		'name'        => 'email_sendmail',
		'title'       => '_SIGNED_MI_EMAIL_SENDMAIL',
		'description' => '_SIGNED_MI_EMAIL_SENDMAIL_DESC',
		'formtype'    => 'text',
		'valuetype'   => 'text',
		'default'     => '/usr/sbin/sendmail'
);

$modversion['config'][] = array(
		'name'        => 'email_queued',
		'title'       => '_SIGNED_MI_EMAIL_QUEUED',
		'description' => '_SIGNED_MI_EMAIL_QUEUED_DESC',
		'formtype'    => 'text',
		'valuetype'   => 'int',
		'default'     => 172800
);

$modversion['config'][] = array(
		'name'        => 'sms_method',
		'title'       => '_SIGNED_MI_SMS_METHOD',
		'description' => '_SIGNED_MI_SMS_METHOD_DESC',
		'formtype'    => 'select',
		'valuetype'   => 'text',
		'options'     => array('Cardboardfish SMS' => 'cardboardfish', 'Internal SIP Network Messaging' => 'sip'),
		'default'     => 'mail'
);


$modversion['config'][] = array(
		'name'        => 'sms_fromnumber',
		'title'       => '_SIGNED_MI_SMS_FROMNUMBER',
		'description' => '_SIGNED_MI_SMS_FROMNUMBER_DESC',
		'formtype'    => 'text',
		'valuetype'   => 'int',
		'default'     => 61000000000
);

$modversion['config'][] = array(
		'name'        => 'cardboardfish_uri',
		'title'       => '_SIGNED_MI_SMS_CARDBOARDFISH_URI',
		'description' => '_SIGNED_MI_SMS_CARDBOARDFISH_URI_DESC',
		'formtype'    => 'text',
		'valuetype'   => 'text',
		'default'     => 'http://sms1.cardboardfish.com:9001/HTTPSMS?'
);

$modversion['config'][] = array(
		'name'        => 'cardboardfish_user',
		'title'       => '_SIGNED_MI_SMS_CARDBOARDFISH_USER',
		'description' => '_SIGNED_MI_SMS_CARDBOARDFISH_USER_DESC',
		'formtype'    => 'text',
		'valuetype'   => 'text',
		'default'     => ''
);

$modversion['config'][] = array(
		'name'        => 'cardboardfish_pass',
		'title'       => '_SIGNED_MI_SMS_CARDBOARDFISH_PASS',
		'description' => '_SIGNED_MI_SMS_CARDBOARDFISH_PASS_DESC',
		'formtype'    => 'password',
		'valuetype'   => 'text',
		'default'     => ''
);


$modversion['config'][] = array(
		'name'        => 'sip_server',
		'title'       => '_SIGNED_MI_SIP_SERVER',
		'description' => '_SIGNED_MI_SIP_SERVER_DESC',
		'formtype'    => 'text',
		'valuetype'   => 'text',
		'default'     => 'voip.dodo.com.au'
);

$modversion['config'][] = array(
		'name'        => 'sip_user',
		'title'       => '_SIGNED_MI_SIP_USER',
		'description' => '_SIGNED_MI_SIP_USER_DESC',
		'formtype'    => 'text',
		'valuetype'   => 'text',
		'default'     => ''
);

$modversion['config'][] = array(
		'name'        => 'sip_pass',
		'title'       => '_SIGNED_MI_SIP_PASS',
		'description' => '_SIGNED_MI_SIP_PASS_DESC',
		'formtype'    => 'password',
		'valuetype'   => 'text',
		'default'     => ''
);


?>